### ISSUE TITLE
Pre meetup

### ISSUE THREAD

**Issue by mcansky** [Bnoure/2ndRound#1]
Ok, c'est parti

### redis

Quelle autre solution pour éviter l'installation de redis dans le système local?

### postgresql

Pas de section concernant PostgreSQL et même question que pour Redis

### Section dupliquée

`touch .env` + la section suivante pourraient être mixée en une

### Procfile et services

Plutôt qu'utiliser `bundle exec sidekiq` vous pouvez utiliser foreman puisqu'il y a un Procfile.
Alternatives:
- https://github.com/DarthSim/overmind (https://kyrylo.org/rails/overmind/2024/02/20/using-overmind-with-foreman-as-a-fallback-for-rails-7-1-apps.html)

### Commits

- certains messages de commits ne décrivent pas tout ce qui est fait dans le commit (css + seeds dans https://github.com/Bnoure/2ndRound/commit/c76dfa080756a631310a28f95eae67a5659711cc); pourquoi faut il éviter le mélange de ce genre de modifications?

### Controllers

- `before_action :authenticate_user!` : quelles autres techniques pourrions nous employer pour limiter les accès à des routes?
- https://github.com/Bnoure/2ndRound/blob/master/app/controllers/seller/games_controller.rb#L11 : le controleur est il le bon endroit pour une méthode d'encoding d'image?

### Views

- `current_user.seller? ? render 'seller_home' : render 'user_home` : une version moche d'un ternaire pour reprendre https://github.com/Bnoure/2ndRound/commit/017c7d241c9ca61dcbdd7b7f0d4de5780c011e3c ; quel autre technique pourrions nous employer pour ne pas se retrouver à faire un `if` dans ce genre de cas?

### services

- https://github.com/Bnoure/2ndRound/blob/master/app/services/attach_game_picture.rb : pas mal, cela dit il y a ici un point de contact assez important avec giantbomb; il y a un bon début de séparation mais est ce que vous voyez un moyen de séparer la partie spécifique à GiantBomb d'une facon qui nous permettre d'etre beaucoup moins dépendant de GiantBomb dans l'absolu?
- https://github.com/Bnoure/2ndRound/blob/master/app/services/get_game_infos.rb : même question pour OpenAi ici, si demain vous vouliez utiliser un autre service comment s'assurer que c'est beaucoup plus facile d'en brancher un autre à la place?

## Conclusion

Voila, un premier survol; le code est relativement light donc je dirais que les points les plus intéressants à discuter sont :
- services
- views
- comment lancer redis + postgresql / setup development env

y a t il d'autres points sur lesquels vous voudriez avoir des réponses / conseils ?

La suite: nous pouvons faire ping/pong sur le ou les sujets qui vous intéresse; on prépare des commits en une ou deux PR; et on présente le patch pendant le meetup ? Chaque PR sera l'occasion d'une discussion avec les gens dans la salle? Voir des implémentations alternatives.

**Comment by Xav-uoafel** [comment]
### Salut !
Je pense que la partie la plus intéressante serait les services, c'est le point central d'une des fonctionnalité clé de l'app. 
Pour ce qui est de **Giantbomb** le problème était de trouver une Api qui puisse nous fournir une Image de bonne qualité tout en ayant une base de donnée assez vaste. C'est la seule que nous ayons pu trouver, dans le temps imparti, qui fasse le job d'où le fait que le code soit très ciblé. Idem pour **OpenAi**.
 Cependant, j'aimerais savoir comment tu aurais décomposé les deux services afin d'être moins dépendant des deux Api.

**Comment by mcansky** [comment]
yes, je pense aussi que c'est le point qui peut être le plus intéressant.

L'approche en général est d'ajouter un degré d'abstraction en utilisant un _pattern_ comme https://refactoring.guru/design-patterns/facade/ruby/example#lang-features. Autrement dit: ajouter une librairie client pour l'API externe.

 Prenons l'exemple d'openAi. Le code est très visible lié à OpenAi et son expression métier est cachée.

Du coup il faut commencer par décomposer le besoin: "Je cherche à avoir des informations sur un jeu dont je fournis la photo".

Donc, coté "GetGameInfos" la responsabilité devrait être "je passe l'image à un autre objet qui va me retourner un Hash de données extraites":
- responsabilité claire
- contrat clair
- testable facilement

Du coup le service qui va gérer la partie "j'envoie la photo et je recupère le retour" a juste cette responsabilité mais pas besoin que GetGameInfos sache que c'est du OpenAI. Pour lui ça serait juste un "PictureDataExtractor". Je pousserai même jusqu'à utiliser le retour d'OpenAI pour instancier un objet spécifique qui retourne juste un hash tout prêt (ce qui permet d'isoler le matching de la regex en dehors du client lui même).

En somme c'est assez proche de ce que vous avez fait mais il y a pas mal de choses faites dans ce petit service:
- init des datas
- création de la requete pour openAi
- traitement de la réponse

est ce que ça vous parle plus?
